id: DC0AF846D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-16T06:02:09+00:00'
last_modified: '2022-05-30T04:46:06.259538+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    fbc0:
      image_group_id: I1PD95942
      title: ཚད་མ་རྣམ་འགྲེལ་གྱི་འགྲེལ་པ།
      total_pages: 1198
      order: 97
      base_file: fbc0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
