id: 094e69d28c054a65a02ea1c1e0bdffb3
initial_creation_type: ocr
source_metadata:
  volumes:
    bf913732eb154cf9a59ae29eca043c1a:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: ཚད་མ་རྣམ་འགྲེལ་གྱི་འགྲེལ་པ།
      total_pages: 1198
      volume_number: 97
